---

- name: Initialize the cluster
  shell: kubeadm init --pod-network-cidr={{ k8s_pod_network_cidr }} >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Create .kube directory
  file: path=$HOME/.kube state=directory mode=0755

- name: Copy admin.conf to user's kube config
  copy: src=/etc/kubernetes/admin.conf dest=$HOME/.kube/config remote_src=yes mode=0600

- name: Install Pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
