---

- name: Add stable chart repo
  community.kubernetes.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Deploy Consul
  community.kubernetes.helm:
    name: consul
    chart_ref: hashicorp/consul
    release_namespace: default
    update_repo_cache: yes
    values:
      global:
        datacenter: regru

      client:
        enabled: true

      server:
        replicas: 1
        bootstrapExpect: 1
        disruptionBudget:
          maxUnavailable: 0
        affinity: ""
        securityContext:
          fsGroup: 2000
          runAsGroup: 2000
          runAsNonRoot: false
          runAsUser: 0

- name: Deploy Vault
  community.kubernetes.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: default
    update_repo_cache: yes
    values:
      server:
        affinity: ""
        ha:
          enabled: true
