---

- name: Add stable chart repo
  community.kubernetes.helm_repository:
    name: traefik
    repo_url: "https://helm.traefik.io/traefik"

- name: Deploy Traefik
  community.kubernetes.helm:
    name: traefik
    chart_ref: traefik/traefik
    chart_version: 9.19.0
    release_namespace: default
    update_repo_cache: yes
    values:
      image:
        name: traefik
        tag: v2.4.8

      deployment:
        enabled: true
        kind: DaemonSet

      providers:
        kubernetesCRD:
          enabled: true
          namespaces:
            - default

      logs:
        general:
          level: ERROR
        access:
          # To enable access logs
          enabled: true
      ports:
        # The name of this one can't be changed as it is used for the readiness and
        # liveness probes, but you can adjust its config to your liking
        traefik:
          port: 9000
          expose: false
          exposedPort: 9000
          protocol: TCP
        metrics:
          port: 8080
          protocol: TCP
        web:
          port: 80
          hostPort: 80
          protocol: TCP
        websecure:
          port: 443
          hostPort: 443
          protocol: TCP
      service:
        enabled: true
        type: ClusterIP
      resources:
        requests:
          cpu: "100m"
          memory: "50Mi"
        limits:
          cpu: "300m"
          memory: "150Mi"
      globalArguments:
        - --metrics.prometheus=true
        - --metrics.prometheus.entryPoint=metrics
        - --certificatesresolvers.letsencrypt.acme.email=dev@clayman.pro
        - --certificatesresolvers.letsencrypt.acme.storage=/tmp/acme.json
        - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      persistence:
        enabled: true
        name: data
      #  existingClaim: ""
        accessMode: ReadWriteOnce
        size: 128Mi
        # storageClass: ""
        path: /data
        annotations: {}
        # subPath: "" # only mount a subpath of the Volume into the pod

      securityContext:
        capabilities:
          drop: [ALL]
        readOnlyRootFilesystem: true
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532

      podSecurityContext:
        fsGroup: 65532
