name: Release

on:
  create:
    tags:
      - v*

jobs:
  lint_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install requirements
        run: make install

      - name: Run linter
        run: make lint

      - name: Publish collection
        env:
          GALAXY_TOKEN: ${{ secrets.GALAXY_TOKEN }}
        run: make publish
